#!/usr/bin/env ansible-playbook

---
- name: Non-Privileged Tasks
  hosts: localhost
  become: False
  tasks:
      - template:
            src: templates/.bash_profile.j2
            dest: "/home/vagrant/.bash_aliases"
            backup: no
      - copy:
            src: files/.gitconfig
            dest: "/home/vagrant/.gitconfig"
            backup: no
      - copy:
            src: files/han-solo.png
            dest: "/home/vagrant/.face"
            backup: no
      - file:
            path: "/home/vagrant/.config/xfce4/terminal"
            state: directory
      - copy:
            src: files/terminalrc
            dest: "/home/vagrant/.config/xfce4/terminal/terminalrc"
            backup: no
      - file:
            path: "/home/vagrant/bin"
            state: directory
      - git:
            repo: "{{ item.repo }}"
            dest: "/home/vagrant/GitHub/{{ item.dest }}"
        loop:
          - { repo: "https://github.com/kurron/ansible-pull-desktop-tweaks.git", dest: "ansible-pull-desktop-tweaks" }
          - { repo: "https://github.com/kurron/ansible-pull-transparent.git", dest: "ansible-pull-transparent" }
          - { repo: "https://github.com/kurron/asciinema-screencasts.git", dest: "asciinema-screencasts" }
          - { repo: "https://github.com/kurron/docker-oracle-jdk-8.git", dest: "docker-oracle-jdk-8" }
          - { repo: "https://github.com/kurron/jvm-development-environment.git", dest: "jvm-development-environment" }
          - { repo: "https://github.com/kurron/lazybones-experiment.git", dest: "lazybones-experiment" }
          - { repo: "https://github.com/kurron/sequence-diagrams.git", dest: "sequence-diagrams" }
          - { repo: "https://github.com/kurron/scripts.git", dest: "scripts" }
          - { repo: "https://github.com/kurron/spring-cloud-aws-echo.git", dest: "spring-cloud-aws-echo" }
          - { repo: "https://github.com/kurron/spring-configuration-files.git", dest: "spring-configuration-files" }
          - { repo: "https://github.com/kurron/tools-groovy.git", dest: "tools-groovy" }
          - { repo: "https://github.com/kurron/tools-java.git", dest: "tools-java" }
          - { repo: "https://github.com/kurron/vagrant-docker-server.git", dest: "vagrant-docker-server" }

          - { repo: "https://github.com/awslabs/git-secrets.git", dest: "git-secrets" }

          - { repo: "https://github.com/kurron/ansible-role-atlassian.git", dest: "ansible-role-atlassian" }
          - { repo: "https://github.com/kurron/ansible-role-artifactory.git", dest: "ansible-role-artifactory" }
          - { repo: "https://github.com/kurron/ansible-role-aws.git", dest: "ansible-role-aws" }
          - { repo: "https://github.com/kurron/ansible-role-base.git", dest: "ansible-role-base" }
          - { repo: "https://github.com/kurron/ansible-role-block-device.git", dest: "ansible-role-block-device" }
          - { repo: "https://github.com/kurron/ansible-role-cpp-developer.git", dest: "ansible-role-cpp-developer" }
          - { repo: "https://github.com/kurron/ansible-role-docker-host.git", dest: "ansible-role-docker-host" }
          - { repo: "https://github.com/kurron/ansible-role-docker-keep-alive.git", dest: "ansible-role-docker-keep-alive-host" }
          - { repo: "https://github.com/kurron/ansible-role-dot-net-developer.git", dest: "ansible-role-dot-net-developer" }
          - { repo: "https://github.com/kurron/ansible-role-dsl-developer.git", dest: "ansible-role-dsl-developer" }
          - { repo: "https://github.com/kurron/ansible-role-elastic-stack.git", dest: "ansible-role-elastic-stack" }
          - { repo: "https://github.com/kurron/ansible-role-go-developer.git", dest: "ansible-role-go-developer" }
          - { repo: "https://github.com/kurron/ansible-role-hashicorp.git", dest: "ansible-role-hashicorp" }
          - { repo: "https://github.com/kurron/ansible-role-javascript-developer.git", dest: "ansible-role-javascript-developer" }
          - { repo: "https://github.com/kurron/ansible-role-jdk.git", dest: "ansible-role-jdk" }
          - { repo: "https://github.com/kurron/ansible-role-jvm-developer.git", dest: "ansible-role-jvm-developer" }
          - { repo: "https://github.com/kurron/ansible-role-jvpn.git", dest: "ansible-role-jvpn" }
          - { repo: "https://github.com/kurron/ansible-role-logfaces.git", dest: "ansible-role-logfaces" }
          - { repo: "https://github.com/kurron/ansible-role-logstash.git", dest: "ansible-role-logstash" }
          - { repo: "https://github.com/kurron/ansible-role-node-js.git", dest: "ansible-role-node-js" }
          - { repo: "https://github.com/kurron/ansible-role-mongodb.git", dest: "ansible-role-mongodb" }
          - { repo: "https://github.com/kurron/ansible-role-mysql.git", dest: "ansible-role-mysql" }
          - { repo: "https://github.com/kurron/ansible-role-operations.git", dest: "ansible-role-operations" }
          - { repo: "https://github.com/kurron/ansible-role-os-limits.git", dest: "ansible-role-os-limits" }
          - { repo: "https://github.com/kurron/ansible-role-plex.git", dest: "ansible-role-plex" }
          - { repo: "https://github.com/kurron/ansible-role-php-developer.git", dest: "ansible-role-php-developer" }
          - { repo: "https://github.com/kurron/ansible-role-python-developer.git", dest: "ansible-role-python-developer" }
          - { repo: "https://github.com/kurron/ansible-role-rabbitmq.git", dest: "ansible-role-rabbitmq" }
          - { repo: "https://github.com/kurron/ansible-role-redis.git", dest: "ansible-role-redis" }
          - { repo: "https://github.com/kurron/ansible-role-resilio-sync.git", dest: "ansible-role-resilio-sync" }
          - { repo: "https://github.com/kurron/ansible-role-rsync.git", dest: "ansible-role-rsync" }
          - { repo: "https://github.com/kurron/ansible-role-ruby-developer.git", dest: "ansible-role-ruby-developer" }
          - { repo: "https://github.com/kurron/ansible-role-software-developer.git", dest: "ansible-role-software-developer" }
          - { repo: "https://github.com/kurron/ansible-role-sql-developer.git", dest: "ansible-role-sql-developer" }
          - { repo: "https://github.com/kurron/ansible-role-time.git", dest: "ansible-role-time" }
          - { repo: "https://github.com/kurron/ansible-role-transparent-huge-pages.git", dest: "ansible-role-transparent-huge-pages" }
          - { repo: "https://github.com/kurron/ansible-role-vpc.git", dest: "ansible-role-vpc" }
          - { repo: "https://github.com/kurron/ansible-role-virtualbox.git", dest: "ansible-role-virtualbox" }

          - { repo: "https://github.com/kurron/terraform-aws-alb.git", dest: "terraform-aws-alb" }
          - { repo: "https://github.com/kurron/terraform-aws-alb-service-attachment.git", dest: "terraform-aws-alb-service-attachment" }
          - { repo: "https://github.com/kurron/terraform-aws-alb-target-group.git", dest: "terraform-aws-alb-target-group" }
          - { repo: "https://github.com/kurron/terraform-aws-api-gateway.git", dest: "terraform-aws-api-gateway" }
          - { repo: "https://github.com/kurron/terraform-aws-api-gateway-binding.git", dest: "terraform-aws-api-gateway-binding" }
          - { repo: "https://github.com/kurron/terraform-aws-api-gateway-deployment.git", dest: "terraform-aws-api-gateway-deployment" }
          - { repo: "https://github.com/kurron/terraform-aws-api-key.git", dest: "terraform-aws-api-key" }
          - { repo: "https://github.com/kurron/terraform-aws-archiving-s3.git", dest: "terraform-aws-archiving-s3" }
          - { repo: "https://github.com/kurron/terraform-aws-bastion.git", dest: "terraform-aws-bastion" }
          - { repo: "https://github.com/kurron/terraform-aws-cloudwatch-log.git", dest: "terraform-aws-cloudwatch-log" }
          - { repo: "https://github.com/kurron/terraform-aws-ec2.git", dest: "terraform-aws-ec2" }
          - { repo: "https://github.com/kurron/terraform-aws-ec2-park.git", dest: "terraform-aws-ec2-park" }
          - { repo: "https://github.com/kurron/terraform-aws-ec2-spot.git", dest: "terraform-aws-spot-park" }
          - { repo: "https://github.com/kurron/terraform-aws-ecs-service.git", dest: "terraform-aws-ecs-service" }
          - { repo: "https://github.com/kurron/terraform-aws-elasticache-redis.git", dest: "terraform-aws-elasticache-redis" }
          - { repo: "https://github.com/kurron/terraform-aws-expiring-s3.git", dest: "terraform-aws-expiring-s3" }
          - { repo: "https://github.com/kurron/terraform-aws-iam.git", dest: "terraform-aws-iam" }
          - { repo: "https://github.com/kurron/terraform-aws-rds-mysql.git", dest: "terraform-aws-rds-mysql" }
          - { repo: "https://github.com/kurron/terraform-aws-security-groups.git", dest: "terraform-aws-security-groups" }
          - { repo: "https://github.com/kurron/terraform-aws-vpc.git", dest: "terraform-aws-vpc" }

          - { repo: "https://github.com/kurron/packer-server-xenial.git", dest: "packer-server-xenial" }
          - { repo: "https://github.com/kurron/packer-xubuntu-xenial.git", dest: "packer-xubuntu-xenial" }

          - { repo: "https://github.com/kurron/cloud-formation-ecs.git", dest: "cloud-formation-ecs" }
          - { repo: "https://github.com/kurron/cloud-formation-rds.git", dest: "cloud-formation-rds" }
          - { repo: "https://github.com/kurron/cloud-formation-full-stack.git", dest: "cloud-formation-full-stack" }
          - { repo: "https://github.com/kurron/cloud-formation-mongodb.git", dest: "cloud-formation-mongodb" }
          - { repo: "https://github.com/kurron/cloud-formation-elasticache.git", dest: "cloud-formation-elasticache" }
          - { repo: "https://github.com/kurron/cloud-formation-elasticsearch.git", dest: "cloud-formation-elasticsearch" }
          - { repo: "https://github.com/kurron/cloud-formation-vpc.git", dest: "cloud-formation-vpc" }
          - { repo: "https://github.com/kurron/cloud-formation-elb.git", dest: "cloud-formation-elb" }
          - { repo: "https://github.com/kurron/cloud-formation-cdn.git", dest: "cloud-formation-cdn" }
          - { repo: "https://github.com/kurron/cloud-formation-waf.git", dest: "cloud-formation-waf" }
          - { repo: "https://github.com/kurron/cloud-formation-ecs-service.git", dest: "cloud-formation-ecs-service" }

          - { repo: "https://github.com/kurron/docker-azul-jdk-8.git", dest: "docker-azul-jdk-8" }
          - { repo: "https://github.com/kurron/docker-azul-jdk-8-build.git", dest: "docker-azul-jdk-8-build" }
          - { repo: "https://github.com/kurron/docker-azul-jdk-9-build.git", dest: "docker-azul-jdk-9-build" }

#     - shell: "cd {{ansible_user_dir}}/GitHub/git-secrets ; make install"

- name: Privileged Tasks
  hosts: localhost
  become: True
  tasks:
      - hostname: name=kal-el
      - lineinfile:
            dest: /etc/hosts
            line: "{{ item }}"
        loop:
          - '192.168.1.222 batcave'
          - '192.168.1.227 stargate'
          - '192.168.1.229 atlantis'
          - '192.168.1.233 bifrost'
          - '192.168.1.234 nas'
          - '192.168.1.235 alfheim'
          - '192.168.1.236 midgard'
          - '192.168.1.237 jotunheim'
          - '192.168.1.240 vanaheim'
          - '192.168.1.250 asgard'
          - '127.0.0.1 kal-el'

- name: Tools (common)
  hosts: localhost
  become: True
  tasks:
      - package:
            name: "{{ item }}"
            state: latest
        loop:
          - tree

- name: Snaps
  hosts: localhost
  become: True
  tasks:
      - command: "snap install {{ item }}"
        loop:
          - vscode
          - sublime-text
          - atom
          - chromium
          - brave
          - datagrip
          - goland
