#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Custom Desktop tweeks
  hosts: Ubuntu 
  sudo: True 
  tasks:
      - name: Add silly environment variable
        lineinfile: dest=/etc/environment line='CUSTOM_RON_WAS_HERE=true'
      - name: Copy Git configuration file
        copy: src=files/.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=644 backup=no
      - name: Copy bashrc change script to a safe place
        copy: src=scripts/append-line-to-bashrc.sh dest=/tmp/append-line-to-bashrc.sh owner=root group=root mode=755 backup=no
      - name: set editor to VI
        command: /tmp/append-line-to-bashrc.sh editor 'set -o vi' 
      - name: Copy login icon  
        copy: src=files/han-solo.png dest=/home/vagrant/.face owner=vagrant group=vagrant backup=no mode=644
      - name: Create the terminal configuration folder 
        file: path=/home/vagrant/.config/xfce4/terminal state=directory group=vagrant owner=vagrant 
      - name: Copy terminal configuration  
        copy: src=files/terminalrc dest=/home/vagrant/.config/xfce4/terminal/terminalrc owner=vagrant group=vagrant backup=no mode=644
      - lineinfile: dest=/etc/hosts line='atlantis 192.168.1.229'
      - lineinfile: dest=/etc/hosts line='batcave 192.168.1.222'
      - lineinfile: dest=/etc/hosts line='docker 192.168.1.233'
      - lineinfile: dest=/etc/hosts line='stargate 192.168.1.227'
      - name: Copy apt configuration file to use the local cache
        copy: src=files/01proxy dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=644 backup=no
      - name: Copy Git script to bin folder 
        copy: src=scripts/git-branch-from-current-work.sh dest=/home/vagrant/bin/git-branch-from-current-work.sh owner=vagrant group=vagrant mode=755 backup=no
      - name: Copy Git script to bin folder 
        copy: src=scripts/git-revert.sh dest=/home/vagrant/bin/git-revert.sh owner=vagrant group=vagrant mode=755 backup=no
      - name: Change the hostname 
        hostname: name=kal-el
      - lineinfile: dest=/etc/hosts line='kal-el 127.0.0.1'
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

