#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Custom Desktop tweeks
  hosts: Ubuntu 
  become: True
  tasks:
      - lineinfile: dest=/etc/environment line='CUSTOM_RON_WAS_HERE=true'
      - copy: src=files/.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=644 backup=no
      - lineinfile: dest=/home/vagrant/.bashrc line="set -o vi"
      - lineinfile: dest=/home/vagrant/.bashrc line="export DOCKER_ID_USER=kurron"
      - copy: src=files/han-solo.png dest=/home/vagrant/.face owner=vagrant group=vagrant backup=no mode=644
      - file: path=/home/vagrant/.config/xfce4/terminal state=directory group=vagrant owner=vagrant
      - copy: src=files/terminalrc dest=/home/vagrant/.config/xfce4/terminal/terminalrc owner=vagrant group=vagrant backup=no mode=644
      - lineinfile: dest=/etc/hosts line='192.168.1.229 atlantis'
      - lineinfile: dest=/etc/hosts line='192.168.1.222 batcave'
      - lineinfile: dest=/etc/hosts line='192.168.1.233 bifrost'
      - lineinfile: dest=/etc/hosts line='192.168.1.227 stargate'
      - lineinfile: dest=/etc/hosts line='192.168.1.236 openvpn'
#     - copy: src=files/01proxy dest=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=644 backup=no
      - file: path=/home/vagrant/bin owner=vagrant group=vagrant state=directory mode=755
      - hostname: name=kal-el
#     - lineinfile: 'dest=/home/vagrant/.bashrc line=export GRADLE_OPTS="-Xmx512m -Dorg.gradle.jvmargs='-Xmx512m -XX:MaxPermSize=128m'"'
      - lineinfile: dest=/etc/hosts line='127.0.0.1 kal-el'
      - git: repo=https://github.com/kurron/jvm-development-environment.git dest=/home/vagrant/GitHub/jvm-development-environment
      - git: repo=https://github.com/kurron/ansible-pull-development.git dest=/home/vagrant/GitHub/ansible-pull-development
      - git: repo=https://github.com/kurron/ansible-pull-docker.git dest=/home/vagrant/GitHub/ansible-pull-docker
      - git: repo=https://github.com/kurron/ansible-pull-operations.git dest=/home/vagrant/GitHub/ansible-pull-operations
      - git: repo=https://github.com/kurron/ansible-pull-transparent.git dest=/home/vagrant/GitHub/ansible-pull-transparent
      - git: repo=https://github.com/kurron/ansible-pull-desktop-tweaks.git dest=/home/vagrant/GitHub/ansible-pull-desktop-tweaks
      - git: repo=https://github.com/kurron/ansible-pull-server-tweaks.git dest=/home/vagrant/GitHub/ansible-pull-server-tweaks
      - git: repo=https://github.com/kurron/scripts.git dest=/home/vagrant/GitHub/scripts
      - git: repo=https://github.com/kurron/docker-oracle-jdk-8.git dest=/home/vagrant/GitHub/docker-oracle-jdk-8
      - git: repo=https://github.com/kurron/sequence-diagrams.git dest=/home/vagrant/GitHub/sequence-diagrams
      - git: repo=https://github.com/kurron/lazybones-experiment.git dest=/home/vagrant/GitHub/lazybones-experiment
      - git: repo=https://github.com/awslabs/git-secrets.git dest=/home/vagrant/GitHub/git-secrets
      - file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory
      - shell: cd /home/vagrant/GitHub/git-secrets ; make install

- name: Tools I Like
  hosts: Ubuntu
  become: True
  tasks:
      - apt: name=tree state=latest
      - apt: name=tmux state=latest
      - apt: name=sysstat state=latest
      - apt: name=iotop state=latest
      - apt: name=iftop state=latest
      - apt: name=wireshark state=latest
      - apt: name=chromium-browser state=latest
      - apt: name=imagemagick state=latest
      - apt: name=gtk-recordmydesktop state=latest
      - apt: name=mplayer state=latest

