#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Non-Privileged Tasks
  hosts: all
  become: False
  tasks:
      - copy:
            src: templates/.bash_profile.j2
            dest: "/home/vagrant/.bash_aliases"
            backup: no
        when: ansible_distribution == "Ubuntu"
      - copy:
            src: templates/.bash_profile.j2
            dest: "/home/vagrant/.bashrc"
            backup: no
        when: ansible_distribution == "Fedora"
      - copy:
            src: files/.gitconfig
            dest: "/home/vagrant/.gitconfig"
            backup: no
      - copy:
            src: files/han-solo.png
            dest: "/home/vagrant/.face"
            backup: no
      - file:
            path: "/home/vagrant/.config/xfce4/terminal"
            state: directory
      - copy:
            src: files/terminalrc
            dest: "/home/vagrant/.config/xfce4/terminal/terminalrc"
            backup: no
      - file:
            path: "/home/vagrant/bin"
            state: directory
      - git:
            repo: "{{ item.repo }}"
            dest: "/home/vagrant/GitHub/{{ item.dest }}"
        with_items:
          - { repo: "https://github.com/kurron/jvm-development-environment.git", dest: "jvm-development-environment" }
          - { repo: "https://github.com/kurron/ansible-pull-desktop-tweaks.git", dest: "ansible-pull-desktop-tweaks" }
          - { repo: "https://github.com/kurron/scripts.git", dest: "scripts" }
          - { repo: "https://github.com/kurron/docker-oracle-jdk-8.git", dest: "docker-oracle-jdk-8" }
          - { repo: "https://github.com/kurron/sequence-diagrams.git", dest: "sequence-diagrams" }
          - { repo: "https://github.com/kurron/lazybones-experiment.git", dest: "lazybones-experiment" }
          - { repo: "https://github.com/kurron/packer-experiment.git", dest: "packer-experiment" }
          - { repo: "https://github.com/kurron/spring-configuration-files.git", dest: "spring-configuration-files" }
          - { repo: "https://github.com/awslabs/git-secrets.git", dest: "git-secrets" }
#     - shell: "cd {{ansible_user_dir}}/GitHub/git-secrets ; make install"

- name: Privileged Tasks
  hosts: all
  become: True
  tasks:
      - hostname: name=kal-el
      - lineinfile:
            dest: /etc/hosts
            line: "{{ item }}"
        with_items:
          - '192.168.1.229 atlantis'
          - '192.168.1.222 batcave'
          - '192.168.1.233 bifrost'
          - '192.168.1.227 stargate'
          - '192.168.1.236 openvpn'
          - '127.0.0.1 kal-el'

- name: Tools (common)
  hosts: all
  become: True
  tasks:
      - package:
            name: "{{ item }}"
            state: latest
        with_items:
          - tree
          - tmux
          - sysstat
          - iotop
          - iftop
          - wireshark

- name: Tools (Ubuntu)
  hosts: Ubuntu
  become: True
  tasks:
      - apt:
          name: "{{ item }}"
          state: latest
        with_items:
            - chromium-browser
            - imagemagick
            - gtk-recordmydesktop
            - mplayer

- name: Tools (CentOS)
  hosts: CentOS
  become: True
  tasks:
      - yum:
            name: "{{ item }}"
            state: latest
        with_items:
          - chromium
          - ImageMagick
          - recordmydesktop

- name: Tools (Fedora)
  hosts: Fedora
  become: True
  tasks:
      - dnf:
            name: "{{ item }}"
            state: latest
        with_items:
          - chromium
          - ImageMagick
          - recordmydesktop

- name: Set Home Folder Permissions (must be last play)
  hosts: all
  become: True
  tasks:
    - file:
          path: /home/vagrant
          owner: vagrant
          group: vagrant
          recurse: true
          state: directory
